name: Run tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      COMPOSER_NO_INTERACTION: 1

    strategy:
      matrix:
        php: [7.3, 7.4, 8.0]
        laravel: [8.*]
        dependency-version: [prefer-lowest, prefer-stable]

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }} (${{ matrix.dependency-version }})

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" --no-update --no-progress
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-progress

      - name: Run tests
        run: vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: Report coverage
        if: matrix.dependency-version == 'prefer-stable'
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage.xml
